import 'package:flutter/material.dart';

var doctors = [
  {
    "id": 1,
    "image": "assets/images/rocknwool-luIDFKHk5zg-unsplash.jpg",
    "name": "Dr. Haylie Siphron",
    "skill": "Dermatologists",
    "review": 540,
    "color1": Colors.yellow,
    "color2": Colors.yellow,
    "color3": Colors.yellow,
    "color4": Colors.yellow,
    "color5": const Color.fromARGB(255, 203, 161, 161),
    "starNB": "4.0 Out of 5.0",
    "specialty": "Asthma & Allergy",
    "Experince": "8 Years ",
    "Patients": "1000+",
    "Available": "(Today at 4 PM)",
    "OT": "30+",
  },
  {
    "id": 2,
    "image": "assets/images/lizzi-sassman-M7ZuRWaaevw-unsplash.jpg",
    "name": "Dr. Corey Aminoff",
    "skill": "Neurologists",
    "review": 310,
    "color1": Colors.yellow,
    "color2": Colors.yellow,
    "color3": Colors.yellow,
    "color4": const Color.fromARGB(255, 203, 161, 161),
    "color5": const Color.fromARGB(255, 203, 161, 161),
    "starNB": "3.0 Out of 5.0",
    "Experince": "8 Years ",
    "Available": "(Today at 4 PM)",
    "specialty": "Headache & Migraine",
    "Patients": "450+",
    "OT": "45+",
  },
  {
    "id": 3,
    "image": "assets/images/seiji-seiji-jAfaZzSQHmY-unsplash.jpg",
    "name": "Dr. Terry Jew",
    "skill": "Dentist",
    "review": 200,
    "color1": Colors.yellow,
    "color2": Colors.yellow,
    "color3": const Color.fromARGB(255, 203, 161, 161),
    "color4": const Color.fromARGB(255, 203, 161, 161),
    "color5": const Color.fromARGB(255, 203, 161, 161),
    "starNB": "2.0 Out of 5.0",
    "Experince": "32 Years ",
    "Available": "(Today at 8 PM)",
    "specialty": "Nerves & Migraine",
    "Patients": "300+",
    "OT": "60+",
  },
  {
    "id": 4,
    "image": "assets/images/hhhh.jpg",
    "name": "Dr. Joseph Brew",
    "skill": "Dentist",
    "review": 350,
    "color1": Colors.yellow,
    "color2": Colors.yellow,
    "color3": Colors.yellow,
    "color4": const Color.fromARGB(255, 203, 161, 161),
    "color5": const Color.fromARGB(255, 203, 161, 161),
    "starNB": "3.0 Out of 5.0",
    "Experince": "25 Years ",
    "Available": "(Today at 5 PM)",
    "specialty": [
      "Dental Implants",
    ],
    "Patients": "500+",
    "OT": "45+",
  },
  {
    "id": 5,
    "image": "assets/images/gggg.jpg",
    "name": "Dr. Corey Aminoff",
    "skill": "Neurologists",
    "review": 150,
    "color1": Colors.yellow,
    "color2": Colors.yellow,
    "color3": const Color.fromARGB(255, 203, 161, 161),
    "color4": const Color.fromARGB(255, 203, 161, 161),
    "color5": const Color.fromARGB(255, 203, 161, 161),
    "starNB": "2.0 Out of 5.0",
    "Experince": "8 Years  ",
    "Available": "(Today at 4 PM)",
    "specialty": "Stomach & Migraine",
    "Patients": "200+",
    "OT": "100+",
  },
  {
    "id": 6,
    "image": "assets/images/hhhh.jpg",
    "name": "Dr. Conney Joe",
    "skill": "Neurologists",
    "review": 20,
    "color1": Colors.white,
    "color2": Colors.white,
    "color3": Colors.white,
    "color4": Colors.white,
    "color5": Colors.white,
    "starNB": "0.0 Out of 5.0",
    "Experince": "6 Years  ",
    "Available": "(Today at 3 PM)",
    "specialty": "Headache & Migraine",
    "Patients": "50+",
    "OT": "30+",
  },
  {
    "id": 7,
    "image": "assets/images/hhhh.jpg",
    "name": "Dr. Ramirez Rain",
    "skill": "Neurologists",
    "review": 750,
    "color1": Colors.yellow,
    "color2": Colors.yellow,
    "color3": Colors.yellow,
    "color4": Colors.yellow,
    "color5": Colors.yellow,
    "starNB": "5.0 Out of 5.0",
    "Experince": "20 Years ",
    "Available": "(Today at 2 PM)",
    "specialty": "Headache & Migraine",
    "Patients": "2000+",
    "OT": "80+",
  },
  {
    "id": 8,
    "image": "assets/images/hhhh.jpg",
    "name": "Dr. Corey Aminoff",
    "skill": "Neurologists",
    "review": 500,
    "color1": Colors.yellow,
    "color2": Colors.yellow,
    "color3": Colors.yellow,
    "color4": Colors.yellow,
    "color5": Colors.white,
    "starNB": "4.0 Out of 5.0",
    "Experince": "15 Years  ",
    "Available": "(Today at 4 PM)",
    "specialty": "Migraine",
    "OT": "45+",
    "Patients": "300+",
  },
];

var chatsData = [
  {
    "image": "assets/images/hhhh.jpg",
    "name": "Dr. Haylie Siphron",
    "skill": "Dermatologists",
    "last_text":
        "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document",
    "date": "1 min ago",
  },
  {
    "image": "assets/images/hhhh.jpg",
    "name": "Dr. Corey Aminoff",
    "skill": "Neurologists",
    "last_text":
        "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document",
    "date": "1 min ago",
  },
  {
    "image": "assets/images/hhhh.jpg",
    "name": "Dr. Corey Aminoff",
    "skill": "Neurologists",
    "last_text":
        "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document",
    "date": "1 min ago",
  },
  {
    "image": "assets/images/hhhh.jpg",
    "name": "Dr. Conney Joe",
    "skill": "Neurologists",
    "last_text":
        "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document",
    "date": "1 min ago",
  },
  {
    "image": "assets/images/hhhh.jpg",
    "name": "Dr. DentTerry Jew",
    "skill": "Dentist",
    "last_text":
        "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document",
    "date": "1 min ago",
  },
  {
    "image": "assets/images/hhhh.jpg",
    "name": "Dr. Corey Aminoff",
    "skill": "Neurologists",
    "last_text":
        "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document",
    "date": "1 min ago",
  },
];
